apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
    - name: cm-test-container
      image: alpine
      command: [ "/bin/sh", "-c", "echo $(STYPE_KEY) $(SLEVEL_KEY)" ]
      env:
        - name: SLEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_LEVEL
        - name: STYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: SPECIAL_TYPE
  restartPolicy: Never